/*
 * This header is generated by weak_classdump 0.2
 * on Friday, June 27, 2014 at 12:46:11 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface _UIGlintyStringView : UIView {
	BOOL _animationRepeats; 
	BOOL _adjustsFontSizeToFitWidth; 
	BOOL _hasCustomBackgroundColor; 
	BOOL _highlight; 
	BOOL _allowsLuminanceAdjustments; 
	BOOL _usesBackgroundDimming; 
	BOOL _needsTextUpdate; 
	BOOL _animating; 
	BOOL _fading; 
	BOOL _showing; 
	id<_UIGlintyStringViewDelegate> _delegate; 
	NSString* _text; 
	UIFont* _font; 
	NSString* _textLanguage; 
	_UILegibilitySettings* _legibilitySettings; 
	_UIVibrantSettings* _vibrantSettings; 
	UIView* _backgroundView; 
	UIColor* _backgroundColor; 
	UIColor* _chevronBackgroundColor; 
	int _chevronStyle; 
	float _horizontalPadding; 
	UILabel* _label; 
	UIView* _spotlightView; 
	int _textIndex; 
	UIImage* _chevron; 
	UIView* _highlightView; 
	UIView* _effectView; 
	UIView* _blurView; 
	float _blurAlpha; 
	NSMutableSet* _blurHiddenRequesters; 
	CGSize _labelSize; 
	CGRect _chevronFrame; 
}
@property (assign,nonatomic) id<_UIGlintyStringViewDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,copy) NSString* text; 				//@synthesize text=_text - In the implementation block
@property (nonatomic,retain) UIFont* font; 				//@synthesize font=_font - In the implementation block
@property (nonatomic,copy) NSString* textLanguage; 				//@synthesize textLanguage=_textLanguage - In the implementation block
@property (nonatomic,copy) CGRect labelFrame; 
@property (assign,nonatomic) CGRect chevronFrame; 				//@synthesize chevronFrame=_chevronFrame - In the implementation block
@property (nonatomic,retain) _UILegibilitySettings* legibilitySettings; 				//@synthesize legibilitySettings=_legibilitySettings - In the implementation block
@property (nonatomic,retain) _UIVibrantSettings* vibrantSettings; 				//@synthesize vibrantSettings=_vibrantSettings - In the implementation block
@property (nonatomic,retain) UIView* backgroundView; 				//@synthesize backgroundView=_backgroundView - In the implementation block
@property (nonatomic,retain) UIColor* backgroundColor; 				//@synthesize backgroundColor=_backgroundColor - In the implementation block
@property (nonatomic,retain) UIColor* chevronBackgroundColor; 				//@synthesize chevronBackgroundColor=_chevronBackgroundColor - In the implementation block
@property (assign,nonatomic) BOOL animationRepeats; 				//@synthesize animationRepeats=_animationRepeats - In the implementation block
@property (assign,nonatomic) BOOL adjustsFontSizeToFitWidth; 				//@synthesize adjustsFontSizeToFitWidth=_adjustsFontSizeToFitWidth - In the implementation block
@property (assign,nonatomic) BOOL hasCustomBackgroundColor; 				//@synthesize hasCustomBackgroundColor=_hasCustomBackgroundColor - In the implementation block
@property (assign,nonatomic) int chevronStyle; 				//@synthesize chevronStyle=_chevronStyle - In the implementation block
@property (assign,nonatomic) float horizontalPadding; 				//@synthesize horizontalPadding=_horizontalPadding - In the implementation block
@property (assign,nonatomic) BOOL highlight; 				//@synthesize highlight=_highlight - In the implementation block
@property (assign,nonatomic) BOOL allowsLuminanceAdjustments; 				//@synthesize allowsLuminanceAdjustments=_allowsLuminanceAdjustments - In the implementation block
@property (assign,nonatomic) BOOL usesBackgroundDimming; 				//@synthesize usesBackgroundDimming=_usesBackgroundDimming - In the implementation block
@property (assign,nonatomic) BOOL needsTextUpdate; 				//@synthesize needsTextUpdate=_needsTextUpdate - In the implementation block
@property (nonatomic,retain) UILabel* label; 				//@synthesize label=_label - In the implementation block
@property (assign,nonatomic) CGSize labelSize; 				//@synthesize labelSize=_labelSize - In the implementation block
@property (nonatomic,retain) UIView* spotlightView; 				//@synthesize spotlightView=_spotlightView - In the implementation block
@property (assign,nonatomic) int textIndex; 				//@synthesize textIndex=_textIndex - In the implementation block
@property (nonatomic,retain) UIImage* chevron; 				//@synthesize chevron=_chevron - In the implementation block
@property (nonatomic,retain) UIView* highlightView; 				//@synthesize highlightView=_highlightView - In the implementation block
@property (assign,nonatomic) BOOL animating; 				//@synthesize animating=_animating - In the implementation block
@property (assign,nonatomic) BOOL fading; 				//@synthesize fading=_fading - In the implementation block
@property (assign,nonatomic) BOOL showing; 				//@synthesize showing=_showing - In the implementation block
@property (nonatomic,retain) UIView* effectView; 				//@synthesize effectView=_effectView - In the implementation block
@property (nonatomic,retain) UIView* blurView; 				//@synthesize blurView=_blurView - In the implementation block
@property (assign,nonatomic) float blurAlpha; 				//@synthesize blurAlpha=_blurAlpha - In the implementation block
@property (nonatomic,retain) NSMutableSet* blurHiddenRequesters; 				//@synthesize blurHiddenRequesters=_blurHiddenRequesters - In the implementation block
-(void)dealloc;
-(void)setBackgroundColor:(id)arg1;
-(void)setDelegate:(id)arg1;
-(void)didMoveToWindow;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1;
-(id)_highlightColor;
-(void)setFont:(id)arg1;
-(void)setText:(id)arg1;
-(void)setAdjustsFontSizeToFitWidth:(BOOL)arg1;
-(void)setBackgroundView:(id)arg1;
-(BOOL)isAnimating;
-(void)stopAnimating;
-(void)startAnimating;
-(void)setAnimating:(BOOL)arg1;
-(void)setLabel:(id)arg1;
-(void)hide;
-(void)fadeOutWithDuration:(double)arg1;
-(void)setChevronStyle:(int)arg1;
-(void)updateText;
-(void)setNeedsTextUpdate:(BOOL)arg1;
-(void)setBlurAlpha:(float)arg1;
-(void)updateBlurForHiddenRequesters;
-(void)hideEffects;
-(void)hideBlur;
-(void)setShowing:(BOOL)arg1;
-(void)showEffects;
-(void)showBlur;
-(void)setFading:(BOOL)arg1;
-(void)fadeInWithDuration:(double)arg1;
-(id)_chevronImageForStyle:(int)arg1;
-(void)setChevron:(id)arg1;
-(void)updateTextWithBounds:(CGRect)arg1;
-(float)_chevronWidthWithPadding;
-(float)_chevronWidthWithPaddingCompression:(float)arg1;
-(float)_chevronHeightWithMaxOffset;
-(void)_updateLabelWithFrame:(CGRect)arg1;
-(float)_chevronVerticalOffset;
-(void)setEffectView:(id)arg1;
-(id)shapeViewForCharactersInString:(id)arg1 withFont:(id)arg2 centeredInFrame:(CGRect)arg3;
-(void)setBlurView:(id)arg1;
-(void)setHighlightView:(id)arg1;
-(id)_highlightCompositingFilter;
-(float)_chevronPadding;
-(float)baselineOffsetFromBottomWithSize:(CGSize)arg1;
-(id)initWithText:(id)arg1 andFont:(id)arg2;
-(void)setTextLanguage:(id)arg1;
-(void)setLegibilitySettings:(id)arg1;
-(void)setVibrantSettings:(id)arg1;
-(void)setBlurHidden:(BOOL)arg1 forRequester:(id)arg2;
-(void)fadeOut;
-(void)fadeIn;
-(void)setHighlight:(BOOL)arg1;
-(void)setHorizontalPadding:(float)arg1;
-(void)_updateHighlight;
-(float)baselineOffsetFromBottom;
-(void)setChevronFrame:(CGRect)arg1;
-(void)setChevronBackgroundColor:(id)arg1;
-(void)setAnimationRepeats:(BOOL)arg1;
-(void)setHasCustomBackgroundColor:(BOOL)arg1;
-(void)setAllowsLuminanceAdjustments:(BOOL)arg1;
-(void)setUsesBackgroundDimming:(BOOL)arg1;
-(void)setLabelSize:(CGSize)arg1;
-(void)setSpotlightView:(id)arg1;
-(void)setTextIndex:(int)arg1;
-(void)setBlurHiddenRequesters:(id)arg1;
@end