/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, June 26, 2014 at 8:52:30 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UIDynamicAnimatorDelegate.h>
#import <_UISettingsKeyObserver.h>
#import <UIGestureRecognizerDelegate.h>

@interface SBLockScreenBounceAnimator : NSObject <UIDynamicAnimatorDelegate, _UISettingsKeyObserver, UIGestureRecognizerDelegate> {
	NSMutableSet* _tapExcludedViews; 
	BOOL _isAnimating; 
	BOOL _bounceEnabled; 
	UIView* _view; 
	SBBouncingSystem* _system; 
	UIDynamicAnimator* _animator; 
	SBBouncingItem* _item; 
	SBBounceBehavior* _behavior; 
	UIGestureRecognizer* _tapRecognizer; 
	NSSet* _gestures; 
	id _shouldBeginBlock; 
	id _prepareBlock; 
	id _translateBlock; 
	id _canceledBlock; 
	id _completedBlock; 
	SBBounceSettings* _settings; 
	id<SBPresentingDelegate> _presentingDelegate; 
}
@property (copy) id shouldBeginBlock; 				//@synthesize shouldBeginBlock=_shouldBeginBlock - In the implementation block
@property (copy) id prepareBlock; 				//@synthesize prepareBlock=_prepareBlock - In the implementation block
@property (copy) id translateBlock; 				//@synthesize translateBlock=_translateBlock - In the implementation block
@property (copy) id canceledBlock; 				//@synthesize canceledBlock=_canceledBlock - In the implementation block
@property (copy) id completedBlock; 				//@synthesize completedBlock=_completedBlock - In the implementation block
@property (nonatomic,retain) SBBounceSettings* settings; 				//@synthesize settings=_settings - In the implementation block
@property (nonatomic,copy) NSSet* tapExcludedViews; 
@property (assign,nonatomic) id<SBPresentingDelegate> presentingDelegate; 				//@synthesize presentingDelegate=_presentingDelegate - In the implementation block
@property (nonatomic,copy) NSSet* gestures; 
-(void)setBounceEnabled:(BOOL)arg1;
-(void)removeTapExcludedView:(id)arg1;
-(void)addTapExcludedView:(id)arg1;
-(void)setShouldBeginBlock:(id)arg1;
-(void)setTranslateBlock:(id)arg1;
-(void)setCompletedBlock:(id)arg1;
-(void)setCanceledBlock:(id)arg1;
-(void)cancelGestureRecognizer:(id)arg1;
-(void)reenableGestureRecognizer:(id)arg1;
-(void)cancelAnimation;
-(void)setPrepareBlock:(id)arg1;
-(void)_createAnimator;
-(void)_addTapRecognizer;
-(void)_removeAnimator;
-(void)_resetAnimator;
-(void)_removeTapRecognizer;
-(void)_beginAnimating:(id)arg1;
-(void)setPresentingDelegate:(id)arg1;
-(void)dealloc;
-(BOOL)gestureRecognizerShouldBegin:(id)arg1;
-(BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
-(BOOL)isAnimating;
-(id)initWithView:(id)arg1;
-(void)dynamicAnimatorDidPause:(id)arg1;
-(void)settings:(id)arg1 changedValueForKey:(id)arg2;
-(void)setSettings:(id)arg1;
-(void)_handleTapGesture:(id)arg1;
-(void)_updateSettings;
@end