/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, June 26, 2014 at 8:52:30 AM Eastern Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol UIDynamicAnimatorDelegate
@optional
-(void)dynamicAnimatorWillResume(id):arg1 ;
-(void)dynamicAnimatorDidPause(id):arg1 ;
@end
